### PR TITLE
Improved extraction of server name and version

### PR DESCRIPTION
**Pull request by kevin39**
Improved _get_service_info_from_discuss.
If asterisk was returning a warning, server version wasn't read properly.

### CODE REVIEW

**Comment by sduthil** [comment]
For reference, the associated ticket is: http://projects.xivo.io/issues/6362

**Comment by elessard1** [comment]
I feel like this could be simplified a little: check if preg_match returns 1, and if it does, assign r['label'] to info[1] and r['version'] to info[2], without any additional checks since checking the preg_match return value is enough.

**Comment by kevin39** [comment]
Of course, you are right. I kept your previous code with same checks. 
I did some optimizations. The code is shorter now ;)

**Comment by elessard1** [comment]
Thanks, I've merged it.

I've also modified a little bit the regex, there was actually a small mistake in the character class, so instead of fixing it I just replaced it with "Asterisk" since, in the end, that's really what we are looking for and this is a stable pattern (i.e. I don't know what was the last time it changed, probably none in the last 5 years).

**Pull request merged**
